### ISSUE TITLE
Search provider freezes gnome-shell on search request.

### ISSUE THREAD

**Issue by tioteath** [muffinmad/pidgin-im-gnome-shell-extension#14]
Looks like the search provider applies some global lock when used. Gnome shell freezes for about 5 seconds.
Steps to reproduce:
- Get a lot of contracts (~1000)
- Enable search provider  in extension preferences
- Try to search something in overview mode
```
gnome-shell --version
GNOME Shell 3.14.2
```

**Comment by geerds** [comment]
same here

**Comment by p91paul** [comment]
@muffinmad Have you any way of being notified by pidgin about modifications to the contact list? I suspect this bug is caused by the fact that you get the list of contacts from pidgin every time the search plugin is called. A cache should solve the issue, but contacts/statuses may stale if there is no way to asyncronously get modifications as they happen.

Another solution could be to get them with a timer every few seconds/minutes, but it is to be tested to not introduce micro-freezes of the whole shell. I have no idea if the gs API offers a way to create a background thread.

**Comment by geerds** [comment]
This should work: https://developer.pidgin.im/doxygen/dev2.x.y/html/blist-signals.html#buddy-added
-- 
Jascha Geerds
jg@ekby.de

**Comment by tioteath** [comment]
> Another solution could be to get them with a timer every few seconds/minutes, but it is to be tested to not introduce micro-freezes of the whole shell. 

Why wouldn't use `inotify` or similar?

**Comment by muffinmad** [comment]
Yes, blist-signals is the right way.

**Comment by brianjmurrell** [comment]
But it doesn't solve the issue of blocking gnome-shell for the initial load of contacts, does it?
